-- CreateTable
CREATE TABLE "creds" (
    "DIALOGFLOW_PROJECT_ID" TEXT NOT NULL,
    "DIALOGFLOW_JSON" TEXT NOT NULL,
    "AZURETTS_SUB_KEY" TEXT NOT NULL,
    "AZURETTS_REGION" TEXT NOT NULL,
    "CLOUDINARY_CLOUD_NAME" TEXT NOT NULL,
    "CLOUDINARY_API_KEY" TEXT NOT NULL,
    "CLOUDINARY_API_SECRET" TEXT NOT NULL,
    "ELEVENLABS" TEXT NOT NULL,
    "OPENAI" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MP3Link" (
    "TYPE" TEXT NOT NULL,
    "KEY" TEXT NOT NULL,
    "VALUE" TEXT NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "creds_DIALOGFLOW_PROJECT_ID_key" ON "creds"("DIALOGFLOW_PROJECT_ID");

-- CreateIndex
CREATE UNIQUE INDEX "creds_DIALOGFLOW_JSON_key" ON "creds"("DIALOGFLOW_JSON");

-- CreateIndex
CREATE UNIQUE INDEX "creds_AZURETTS_SUB_KEY_key" ON "creds"("AZURETTS_SUB_KEY");

-- CreateIndex
CREATE UNIQUE INDEX "creds_AZURETTS_REGION_key" ON "creds"("AZURETTS_REGION");

-- CreateIndex
CREATE UNIQUE INDEX "creds_CLOUDINARY_CLOUD_NAME_key" ON "creds"("CLOUDINARY_CLOUD_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "creds_CLOUDINARY_API_KEY_key" ON "creds"("CLOUDINARY_API_KEY");

-- CreateIndex
CREATE UNIQUE INDEX "creds_CLOUDINARY_API_SECRET_key" ON "creds"("CLOUDINARY_API_SECRET");

-- CreateIndex
CREATE UNIQUE INDEX "creds_ELEVENLABS_key" ON "creds"("ELEVENLABS");

-- CreateIndex
CREATE UNIQUE INDEX "creds_OPENAI_key" ON "creds"("OPENAI");

-- CreateIndex
CREATE UNIQUE INDEX "MP3Link_KEY_key" ON "MP3Link"("KEY");

-- CreateIndex
CREATE UNIQUE INDEX "MP3Link_VALUE_key" ON "MP3Link"("VALUE");
